### ISSUE TITLE
Au niveau des images (no sql)

### ISSUE THREAD

**Issue by Fab16BSB** [override-community/ProgEnImages#11]
Chaque image doit avoir : 
- une url pointant vers son visuel
- des commentaires (non récursif on peut pas repondre aux autre)
- une date d'ajout
- une description (definition du concept) donc traduite dans plusieurs langue
- un auteur
- un nombre de vue
- un nombre de téléchargement
- plusieurs themes (exemple prog, POO....)

**Comment by TLouvet** [comment]
A respécifier sur du SQL
