### ISSUE TITLE
English + Spanish

### ISSUE THREAD

**Issue by Fab16BSB** [override-community/ProgEnImages#6]
Ajouter la possibilité de changer de langue : french, english or spanish via un menu déroulant dans le header (au à droite).
Chaque langue (FR, EN, ES) sera précédé d'un petit drapeau.
Ce qui aura pour effet de traduire tout le site sauf les commentaires présent sur les images.
De plus on aura une nouvelle structure pour stocker nos images un dossier racine appelé images ainsi que des sous dossier en rapport avec la langue (fr, en, es) il faudra donc charger les bonnes images en fonction de la langue.

**Comment by TLouvet** [comment]
suppression de la structure des dossiers images avec passage sur CMS backend qui va gérer les différentes entrées de langue
seul le front aura un choix de locale, qui se répercutera directement dans l'url ex : progenimage/fr ou progenimage/es , etc.
