### ISSUE TITLE
Ajouter un element indiquant les nouvelle images

### ISSUE THREAD

**Issue by Fab16BSB** [override-community/ProgEnImages#8]
Sur certaine carte indiquer lesquels sont nouvelle via une étiquette (new, nouveau...).
De mon point de vue cela doit se faire automatiquement via la base de données.
Plusieurs possibilité à en discuter : 

- Fixé la date à une semaine
- Fixé la date à un mois
- Un lot d'image est nouveau jusqu'à l'ajout d'une autre lot.

**Comment by TLouvet** [comment]
@Fab16BSB je pense qu'il faut garder une fixation temporelle, mais pas l'override dès qu'on ajoute une image nouvelle.

Pour cela je ne pense pas qu'on retienne la troisième option: 
Imagine que tu ajoutes un lot d'images le lundi matin.... Puis à 14h tu te rends compte qu'il en manque une, tu l'ajoutes et hop, c'est comme un nouveau lot, toutes tes images du matin ne sont plus marquées en tant que nouveauté.

Alors que si tu retiens une option temporelle, alors c'est très simple de savoir si une image est nouvelle ou non

**Comment by TLouvet** [comment]
Solution temporaire:  toute image publiée il y a moins de 7 jours, à voir si on étend ou non
